[ADD] Added dashboard and fix buyAndSellApi
savoirfairelinux/formationpython pull request #23
Opened 2019-11-06 22:51 UTC by lgharib

2019-11-07 15:13 UTC, eilst requested changes

2019-11-07 15:13 UTC, eilst commented on .idea/.gitignore
> +# Default ignored files
Hey, if you could remove everything under .idea.

2019-11-07 15:14 UTC, eilst commented on .idea/.gitignore
> +# Default ignored files
you can do it manually here (6 commits) and then we squash it... but it would be better if you do it in your terminal

2019-11-12 13:59 UTC, larbizard approved these changes

2019-11-12 14:00 UTC, merged